### ISSUE TITLE
White screen upon searching anything

### ISSUE THREAD

**Issue by clubby789** [BloodHoundAD/BloodHound#417]
Upon searching anything in Bloodhound (4.0.1-0kali1) the screen turns white. ctrl-r reloads it, but the issue happens again. The JS console reports:
![image](https://user-images.githubusercontent.com/13556931/103172563-4b1f7800-484c-11eb-85bb-5404fa09d2f5.png)

**Comment by init5-msft** [comment]
Same thing happens with me, but not from the normal search though, when I create a new Edge and start filling the Source Node or Target Node, those crash bloodhound.

Same exact view: a blank white screen.

**Comment by ecote7** [comment]
I have the same issue...but when I use another remote Neo4j instance (which I don't have complete access for the moment, to get more details) it works...no more white screen after a search. Maybe this information may helps others.

**Comment by 4f-kira** [comment]
Same white screen  happens with me.

**Comment by ajkerley628** [comment]
I am also experiencing this issue. I had to downgrade to a previous snapshot.

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/BloodHound/commit/4a0cd8196a9bad1380aedbd6c1cc65f56a5ffca9.

You can grab rolling release until we tag a new release here: https://github.com/BloodHoundAD/BloodHound/releases/tag/BloodHound-Rolling

**Comment by izysec** [comment]
Hi, I believe the problem might still persist. Just grabbed the latest rolling release at this time, 0b2754f, but still facing the same error when trying to add a new edge. Exactly what @init5-msft described above

**Comment by 0x1Nj3cT0R** [comment]
I'm having the same issue. Build it from source (latest build 0b2754f).
![image](https://user-images.githubusercontent.com/66210287/107367290-ccbf2280-6ae7-11eb-8d16-6450ce01059d.png)

**Comment by phackt** [comment]
Same here, white screen with last release when searching for a node
