### ISSUE TITLE
LDAP Exception in Loop: 87. (null). The search filter is invalid.. Filter: (samaccountname=).

### ISSUE THREAD

**Issue by Muath1412** [BloodHoundAD/BloodHound#510]
Hi,
I'm facing this issue with newest sharphound collector:
```
2022-02-13T17:19:28.9096676+03:00|INFORMATION|Status: 68549 objects finished (+3530 378.7238)/s -- Using 210 MB RAM
2022-02-13T17:19:38.0704310+03:00|WARNING|[CommonLib LDAPUtils]LDAP Exception in Loop: 87. (null). The search filter is invalid.. Filter: (samaccountname=). Domain: XXXXXXX
System.DirectoryServices.Protocols.LdapException: The search filter is invalid.
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at SharpHoundCommonLib.LDAPUtils.<QueryLDAP>d__33.MoveNext() in D:\a\SharpHoundCommon\SharpHoundCommon\src\CommonLib\LDAPUtils.cs:line 833
```

then it stopped fetching the data.

**Comment by 08AyA08** [comment]
Similar issue for me but "CommonLib LDAPUtils]LDAP Exception in Loop: 81. (null). The LDAP server is unavailable".  This is using SharpHound 1.0.3

**Comment by duncandw** [comment]
Same error with sharphound.exe 1.0.3;

$Domain = "ANONYMOUSDOMAIN.NET"
$Scope = "GLOBAL"

..\SharpHound.exe --collectionmethods DCOnly --domain $Domain --outputprefix $Scope"_DCOnly" --collectallproperties --statusinterval 5000 -v 2

2022-03-10T08:15:56.0252415+00:00|INFORMATION|Status: 663 objects finished (+181 12.75)/s -- Using 106 MB RAM
2022-03-10T08:15:59.0326255+00:00|WARNING|[CommonLib LDAPUtils]LDAP Exception in Loop: 87. (null). The search filter is
invalid.. Filter: (samaccountname=). Domain: ANONYMOUSDOMAIN.NET
System.DirectoryServices.Protocols.LdapException: The search filter is invalid.
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at SharpHoundCommonLib.LDAPUtils.<QueryLDAP>d__33.MoveNext()

**Comment by Muath1412** [comment]
Hi,

did anyone got around this error?

**Comment by JBalanza** [comment]
Same error here, 

Using the latest build 1.0.3 of Sharphound. I used the following cmdline:

`SharpHound.exe -c DCOnly --stealth --randomfilenames --zipfilename enum --zippassword test --secureldap --throttle 30000`

With the following error:

`[WARNING][CommonLib LDAPUtils] LDAP Exception in loop 87. (null). O filtro de pesquisa ? invalido.. Filter: (samaccountname=). DOMAIN: <redacted>`

Regards

**Comment by clod81** [comment]
getting the same. any clue?

**Comment by 08AyA08** [comment]
not sure if it helps but I tried this initially using kali while on vpn.  had to install bloodhound on a physically connected internal machine to get sharphound to work.

**Comment by TaylorHassall** [comment]
Had the same issue after initially running `Invoke-Bloodhound -CollectionMethod DCOnly`. This process completed and generated data with no issue so I attempted to run `Invoke-Bloodhound -CollectionMethod DCOnly -Loop -Loopduration 00:30:00`, then got the error. 

Stopped the sharphound.ps1 process then cleared out existing .json, and zipped data, as well as the .bin file that was generated. Ran it again in a fresh Terminal and it ran fine once again. Running it with the `-Loop -Loopduration 00:30:00` afterwards failed once more. 

I cleared out the files, fresh Terminal again, ran `Invoke-Bloodhound -CollectionMethod DCOnly -Loop -Loopduration 00:30:00` The first collection runs, but when it closes it's writers for the first time it fails to run afterwards reporting `|WARNING|[CommonLib LDAPUtils]LDAP Exception in Loop: 87. (null). The search filter is invalid.. Filter: (|). Domain: domain.local
System.DirectoryServices.Protocols.LdapException: The search filter is invalid.
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at SharpHoundCommonLib.LDAPUtils.<QueryLDAP>d__32.MoveNext()`

**Comment by rvazarkar** [comment]
I'm pretty sure I know what's causing this. Good news is it shouldn't be
affecting anything, it's just annoying. It should be fixed in the next
version

**Comment by TaylorHassall** [comment]
> I'm pretty sure I know what's causing this. Good news is it shouldn't be affecting anything, it's just annoying. It should be fixed in the next version

Champion! I didn't think it was affecting anything, I was still getting items collected at least from the initial collections and it seemed to be in line with the amount of items I knew we had. Thanks a tonne for your work!

**Comment by JonasBK** [comment]
Closing this one as this issue should have been fixed in the latest version.
